name: Issues

on: [push]
  # schedule:
  # - cron: "0 12 1 * *"
  #

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: uksf/stale@v1.1.2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has been automatically marked as stale because it has been open for 60 days without activity. Remove the stale label or make a comment, otehrwise this issue will be closed in 30 days.'
        days-before-stale: 60
        days-before-close: 30
        stale-issue-label: 'status/stale'
        exempt-issue-labels: 'type/bug,status/ongoing'
